### ISSUE TITLE
Params are incorrect

### ISSUE THREAD

**Issue by geekalert** [rakheshster/iTerm2WindowsTerminal#2]
I appreciate this script so much! ONe thing I had to learn, though, was that `-ConfigFileURL` and `-ConfigFile` are not the params that the script expects. When I looked closely at your screenshot and then looked at teh script itself, I realized that the switches are actually `colorFileURL` and `colorFile`. After I began using that convention, it worked flawlessly. Thank you again!

**Comment by rakheshster** [comment]
Thanks for this. :) So sorry I had the wrong parameters in the README and you ended up wasting time. I've fixed the README now.
